=== Gamelena/tangerine-testing/web/application/components/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="component" type="componentType">
    </xsd:element>
    <xsd:complexType name="componentType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="elements" type="elementsType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="searchers" type="searchersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="forms" type="formsType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="script" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pane" type="paneType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="target" use="required" type="xsd:normalizedString"/>
        <xsd:attribute name="type" use="required" type="componentTypeType" />
        <xsd:attribute name="name" type="xsd:normalizedString" />
        <xsd:attribute name="list" type="xsd:boolean" />
        <xsd:attribute name="edit" type="xsd:boolean" />
        <xsd:attribute name="add" type="xsd:boolean"/>
        <xsd:attribute name="delete" type="xsd:boolean"/>
        <xsd:attribute name="clone" type="xsd:boolean"/>
        <xsd:attribute name="canSort" type="xsd:boolean"/>
        <xsd:attribute name="js" />
        <xsd:attribute name="jsForm" />
        <xsd:attribute name="style" />
        <xsd:attribute name="plugins" />
        <xsd:attribute name="containerDojoType" type="containerDojoTypeType" />
        <xsd:attribute name="chartXType" />
        <xsd:attribute name="chartXTarget" />
        <xsd:attribute name="chartXLabel" />
        <xsd:attribute name="chartYTarget" />
        <xsd:attribute name="chartYLabel" />
        <xsd:attribute name="chartItems" />
        <xsd:attribute name="onRowClick" />
        <xsd:attribute name="onRowDblClick" />
        <xsd:attribute name="onFetchComplete" />
        <xsd:attribute name="onShow" />
        <xsd:attribute name="cols" />
        <xsd:attribute name="titles" />
        <xsd:attribute name="items" />
        <xsd:attribute name="itemsDescription" />
        <xsd:attribute name="aclComponent" />
        <xsd:attribute name="serverPagination" type="xsd:boolean" />
        <xsd:attribute name="inheritsData" type="xsd:boolean" />
        <xsd:attribute name="chartDojoType" type="chartDojoTypeType" />
        <xsd:attribute name="chartDojoTheme" type="chartDojoThemeType" />
    </xsd:complexType>
    <xsd:complexType name="elementsType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="style" />
    </xsd:complexType>
    <xsd:complexType name="searchersType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="hideSubmit" type="xsd:boolean"/>
        <xsd:attribute name="outsideContent" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:complexType name="formsType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="changePassword" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="edit" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="add" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onPostSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onShow" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="tabs" type="tabsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="ajax" type="xsd:boolean" />
        <xsd:attribute name="style"/>
        <xsd:attribute name="onload"/>
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
        <xsd:attribute name="component"/>
    </xsd:complexType>
    <xsd:complexType name="formType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tabs" type="tabsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="onPostSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="ajax" />
        <xsd:attribute name="style"/>
        <xsd:attribute name="onload"/>
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
    </xsd:complexType>
    <xsd:complexType name="helpersType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="dialog" type="formsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="customFunction" type="customFunctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="excel" type="excelType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="uploader" type="uploaderType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="PaneType">
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
        <xsd:attribute name="name"/>
    </xsd:complexType>
    <xsd:complexType name="tabsType">
        <xsd:sequence>
            <xsd:element name="tab" type="tabType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tabType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="onClick" />
        <xsd:attribute name="dojoType" />
        <xsd:attribute name="style" />
    </xsd:complexType>
    <xsd:complexType name="paneType">
        <xsd:attribute name="name" />
        <xsd:attribute name="href" />
        <xsd:attribute name="onshow" />
    </xsd:complexType>
    <xsd:complexType name="groupType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="type" type="elementTypeType"/>
        <xsd:attribute name="visible" type="xsd:boolean" />
        <xsd:attribute name="edit" type="editType" />
        <xsd:attribute name="add" type="editType" />
        <xsd:attribute name="clone" type="editType" />
        <xsd:attribute name="password" />
        <xsd:attribute name="defaultValue" />
        <xsd:attribute name="defaultText" />
        <xsd:attribute name="field" />
        <xsd:attribute name="required" type="xsd:boolean" />
        <xsd:attribute name="disabled" type="xsd:boolean" />
        <xsd:attribute name="readonly" type="xsd:boolean" />
        <xsd:attribute name="regExp"/>
        <xsd:attribute name="trim" type="xsd:boolean"/>
        <xsd:attribute name="table"/>
        <xsd:attribute name="tableField"/>
        <xsd:attribute name="tablePk"/>
        <xsd:attribute name="tableMethod"/>
        <xsd:attribute name="invalidMessage"/>
        <xsd:attribute name="promptMessage"/>
        <xsd:attribute name="list"/>
        <xsd:attribute name="formatter"/>
        <xsd:attribute name="maxlength"/>
        <xsd:attribute name="width"/>
        <xsd:attribute name="operator" type="operatorType"/>
    </xsd:complexType>
    <xsd:complexType name="customFunctionType">
        <xsd:attribute name="target"/>
        <xsd:attribute name="onclick"/>
        <xsd:attribute name="name"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="title"/>
        <xsd:attribute name="disabled" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:complexType name="excelType">
        <xsd:attribute name="name"/>
        <xsd:attribute name="formatter" type="excelFormatter"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="disabled" type="xsd:boolean"/>
    </xsd:complexType>
        <xsd:complexType name="uploaderType">
        <xsd:attribute name="name"/>
        <xsd:attribute name="path"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="action" type="uploaderActionType"/>
        <xsd:attribute name="processClass"/><!-- @todo por implementar -->
        <xsd:attribute name="processMethod"/><!-- @todo por implementar -->
        <xsd:attribute name="truncate" type="xsd:boolean" />
    </xsd:complexType>
    <xsd:complexType name="elementType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="tinyMceInit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="thumb" type="thumbType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="target" use="required"/>
        <xsd:attribute name="type" type="elementTypeType"/>
        <xsd:attribute name="style" />
        <xsd:attribute name="name" />
        <xsd:attribute name="visible" type="xsd:boolean" />
        <xsd:attribute name="edit" type="editType" />
        <xsd:attribute name="add" type="editType" />
        <xsd:attribute name="clone" type="editType" />
        <xsd:attribute name="value" />
        <xsd:attribute name="defaultValue" />
        <xsd:attribute name="uncheckedValue" />
        <xsd:attribute name="selectedTitle" type="xsd:string"/>
        <xsd:attribute name="unselectedTitle" type="xsd:string" />
        <xsd:attribute name="defaultText" type="xsd:string" />
        <xsd:attribute name="field" />
        <xsd:attribute name="onchange" />
        <xsd:attribute name="disabled" type="xsd:boolean" />
        <xsd:attribute name="onclick" />
        <xsd:attribute name="onkeypress" />
        <xsd:attribute name="onkeyup" />
        <xsd:attribute name="onblur" />
        <xsd:attribute name="onload" />
        <xsd:attribute name="required" type="xsd:boolean" />
        <xsd:attribute name="autocomplete" type="onOffType" />
        <xsd:attribute name="regExp"/>
        <xsd:attribute name="trim"/>
        <xsd:attribute name="url" type="xsd:anyURI"/>
        <xsd:attribute name="path"/>
        <xsd:attribute name="table"/>
        <xsd:attribute name="tableField"/>
        <xsd:attribute name="tablePk"/>
        <xsd:attribute name="tableMethod"/>
        <xsd:attribute name="invalidMessage"/>
        <xsd:attribute name="promptMessage"/>
        <xsd:attribute name="list"/>
        <xsd:attribute name="data"/>
        <xsd:attribute name="formatter"/>
        <xsd:attribute name="maxlength" type="xsd:integer"/>
        <xsd:attribute name="width"/>
        <xsd:attribute name="checked" type="xsd:boolean"/>
        <xsd:attribute name="sufix"/>
        <xsd:attribute name="prefix"/>
        <xsd:attribute name="tinyMceTemplate" />
        <xsd:attribute name="placeHolder" />
        <xsd:attribute name="operator" type="operatorType"/>
    </xsd:complexType>
    <xsd:complexType name="thumbType">
        <xsd:attribute name="width" />
        <xsd:attribute name="height" />
        <xsd:attribute name="path"/>
    </xsd:complexType>
    <xsd:simpleType name="onOffType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="on"/>
            <xsd:enumeration value="off"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="editType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true"/>
            <xsd:enumeration value="false"/>
            <xsd:enumeration value="readonly"/>
            <xsd:enumeration value="disabled"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="uploaderActionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="load"/>
            <xsd:enumeration value="insert"/>
            <xsd:enumeration value="delete"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="excelFormatter">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Excel5"/>
            <xsd:enumeration value="Excel2007"/>
            <xsd:enumeration value="csv"/>
            <xsd:enumeration value="html"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="operatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="like"/>
            <xsd:enumeration value="between"/>
            <xsd:enumeration value="="/>
            <xsd:enumeration value="!="/>
            <xsd:enumeration value="&amp;gt;&amp;lt;"/>
            <xsd:enumeration value="&amp;gt;"/>
            <xsd:enumeration value="&amp;lt;"/>
            <xsd:enumeration value="&#38;gt;="/>
            <xsd:enumeration value="&#38;lt;="/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="componentTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dojo-chart"/>
            <xsd:enumeration value="dojo-settings"/>
            <xsd:enumeration value="dojo-simple-crud"/>
            <xsd:enumeration value="nodes-graph"/>
            <xsd:enumeration value="php-info"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="elementTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dijit-form-check-box"/>
            <xsd:enumeration value="dojox-form-checked-multi-select"/>
            <xsd:enumeration value="dojox-form-checked-multi-select-binary"/>
            <xsd:enumeration value="dijit-form-combo-box"/>
            <xsd:enumeration value="dijit-form-date-text-box"/>
            <xsd:enumeration value="dijit-form-filtering-select"/>
            <xsd:enumeration value="dijit-form-select"/>
            <xsd:enumeration value="dijit-form-textarea"/>
            <xsd:enumeration value="dijit-form-time-text-box"/>
            <xsd:enumeration value="dijit-form-validation-text-box"/>
            <xsd:enumeration value="dojox-form-uploader"/>
            <xsd:enumeration value="dojox-widget-color-picker"/>
            <xsd:enumeration value="dojo-dnd-source"/>
            <xsd:enumeration value="hidden"/>
            <xsd:enumeration value="list-files"/>
            <xsd:enumeration value="tiny-mce"/>
            <xsd:enumeration value="zwei-form-validation-textarea"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="chartDojoTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Areas"/>
            <xsd:enumeration value="Bars"/>
            <xsd:enumeration value="Base"/>
            <xsd:enumeration value="Bubble"/>
            <xsd:enumeration value="Candlesticks"/>
            <xsd:enumeration value="CartesianBase"/>
            <xsd:enumeration value="ClusteredBars"/>
            <xsd:enumeration value="ClusteredColumns"/>
            <xsd:enumeration value="Columns"/>
            <xsd:enumeration value="Default"/>
            <xsd:enumeration value="Grid"/>
            <xsd:enumeration value="Lines"/>
            <xsd:enumeration value="Markers"/>
            <xsd:enumeration value="MarkersOnly"/>
            <xsd:enumeration value="OHLC"/>
            <xsd:enumeration value="Pie"/>
            <xsd:enumeration value="Scatter"/>
            <xsd:enumeration value="Spider"/>
            <xsd:enumeration value="Stacked"/>
            <xsd:enumeration value="StackedAreas"/>
            <xsd:enumeration value="StackedBars"/>
            <xsd:enumeration value="StackedColumns"/>
            <xsd:enumeration value="StackedLines"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="chartDojoThemeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Adobebricks"/>
            <xsd:enumeration value="Algae"/>
            <xsd:enumeration value="Bahamation"/>
            <xsd:enumeration value="BlueDusk"/>
            <xsd:enumeration value="Charged"/>
            <xsd:enumeration value="Chris"/>
            <xsd:enumeration value="Claro"/>
            <xsd:enumeration value="CubanShirts"/>
            <xsd:enumeration value="Desert"/>
            <xsd:enumeration value="Distinctive"/>
            <xsd:enumeration value="Dollar"/>
            <xsd:enumeration value="Electric"/>
            <xsd:enumeration value="Grasshoper"/>
            <xsd:enumeration value="Grasslands"/>
            <xsd:enumeration value="GreySkies"/>
            <xsd:enumeration value="Harmony"/>
            <xsd:enumeration value="IndigoNation"/>
            <xsd:enumeration value="Ireland"/>
            <xsd:enumeration value="Julie"/>
            <xsd:enumeration value="MiamiNice"/>
            <xsd:enumeration value="Midwest"/>
            <xsd:enumeration value="Minty"/>
            <xsd:enumeration value="PrimaryColors"/>
            <xsd:enumeration value="PurpleRain"/>
            <xsd:enumeration value="Renkoo"/>
            <xsd:enumeration value="RoyalPurples"/>
            <xsd:enumeration value="SageToLime"/>
            <xsd:enumeration value="Shrooms"/>
            <xsd:enumeration value="Threed"/>
            <xsd:enumeration value="Tom"/>
            <xsd:enumeration value="Tufte"/>
            <xsd:enumeration value="WatersEdge"/>
            <xsd:enumeration value="Wetland"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="containerDojoTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dijit/layout/BorderContainer"/>
            <xsd:enumeration value="dijit/layout/AccordionContainer"/>
            <xsd:enumeration value="dijit/layout/TabContainer"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Gamelena/tangerine-testing/web/application/components/modules.xml
<?xml version="1.0"?>
<component name="M&amp;oacute;dulos" type="dojo-simple-crud"
    target="AclModulesModel" list="true" edit="true" add="true" delete="true"
    clone="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="components.xsd">
    <elements>
        <element name="ID" target="id"
            type="dijit-form-validation-text-box" visible="true" edit="false"
            add="false" />
        <element name="M&amp;oacute;dulo Padre" target="parent_id"
            type="dijit-form-filtering-select" table="AclModulesModel"
            tableMethod="selectDistinct" defaultValue="" defaultText="---Ninguno---"
            field="parent_title" visible="true" edit="true" add="true"
            clone="true" />
        <element name="M&amp;oacute;dulo Padre" target="parent.title"
            type="dijit-form-validation-text-box" visible="false" edit="false"
            add="false" />
        <element name="M&amp;oacute;dulo" target="title"
            type="dijit-form-validation-text-box" visible="true" edit="true"
            add="true" clone="true" />
        <element name="M&amp;oacute;dulo" target="acl_modules.title"
            type="dijit-form-validation-text-box" visible="false" edit="false"
            add="false" />
        <element name="Componente" target="module"
            type="dijit-form-validation-text-box" visible="true" edit="true"
            add="true" clone="true" />
        <element name="Componente" target="acl_modules.module"
            type="dijit-form-validation-text-box" visible="false" edit="false"
            add="false" />
        <element name="En &amp;Aacute;rbol" target="tree"
            type="dijit-form-check-box" formatter="utils.formatYesNo"
            visible="true" edit="true" add="true" clone="true" />
        <element name="Refrescar al cargar" target="refresh_on_load"
            type="dijit-form-check-box" formatter="utils.formatYesNo"
            visible="true" edit="true" add="true" clone="true" />
        <element name="Tipo" target="type"
            type="dijit-form-filtering-select" list="xml;zend_module;legacy;iframe"
            defaultValue="" defaultText="---Ninguno---" visible="true"
            edit="true" add="true" clone="true" />
        <element name="Aprobado" target="approved" type="dijit-form-check-box"
            formatter="utils.formatYesNo" visible="true" edit="true"
            add="true" clone="true" />
        <element name="Root" target="root" type="dijit-form-check-box"
            formatter="utils.formatYesNo" visible="true" edit="true"
            add="true" clone="true" />
        <element name="Usa Owner" target="ownership" type="dijit-form-check-box"
            formatter="utils.formatYesNo" visible="true" edit="true"
            add="true" clone="true" />
        <element name="Orden" target="order"
            type="dijit-form-validation-text-box" regExp="[\d]+"
            invalidMessage="Solo números" visible="false" edit="true"
            add="true" clone="true" />
        <element name="Acciones" target="actions"
            type="dojox-form-checked-multi-select" table="AclActionsModel"
            visible="false" edit="true" add="true" clone="true" />
        <element name="&amp;Iacute;cono" target="icons_id"
            field="image" type="dijit-form-filtering-select" formatter="utils.formatImage16"
            table="IconsModel" visible="true" defaultValue=""
            defaultText="---Ninguno---" edit="true" add="true" clone="true" />
    </elements>
    <searchers>
        <group name="Buscar">
            <element target="acl_modules.title" />
            <element target="parent.title" />
            <element target="acl_modules.module" operator="=" />
        </group>
    </searchers>
    <forms ajax="true">
        <tabs>
            <tab name="General">
                <element target="parent_id" />
                <element target="title" />
                <element target="module" />
                <element target="tree" />
                <element target="refresh_on_load" />
                <element target="type" />
                <element target="root" />
                <element target="ownership" />
                <element target="approved" />
                <element target="order" />
            </tab>
            <tab name="Acciones">
                <element name=" " target="actions" style="width:200px;" />
            </tab>
            <tab name="&amp;Iacute;cono">
                <element name=" " target="icons_id" />
            </tab>
            <tab name="Contenido">
                <element name=" " target="content"
                    type="dijit-form-textarea" edit="true"
                    add="true"
                    style="min-width:60em;min-height:20em;font-family:sans-serif;color:#406b9b;"
                    required="false" disabled="true" clone="true" />
            </tab>
        </tabs>
        <onShow>
            if (this.getChildrenByName('data[content]').length) {
                var content = this.getChildrenByName('data[content]')[0];
                content.set('required', false);
                var row = content.domNode.parentNode;
                row.title='Doble Click para editar';
                row.ondblclick=function(e) {
                    content.set('disabled', !content.get('disabled'));
                    if (content.get('disabled')) {
                        row.title='Doble Click para editar.';
                    } else {
                        row.title='Doble Click para cancelar edición (se ignorarán los cambios).';
                    }
                };
            }
        </onShow>
    </forms>
</component>

=== Gamelena/tangerine-testing/web/application/components/users.xml
<?xml version="1.0"?>
<component name="Usuarios" type="dojo-simple-crud" target="AclUsersModel"
	list="true" edit="true" add="true" delete="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="components.xsd">
	<elements>
		<element name="Usuario" target="user_name"
			type="dijit-form-validation-text-box" visible="true" edit="false"
			add="true" required="true" />
		<element name="Nombres" target="first_names"
			type="dijit-form-validation-text-box" visible="true" edit="true" add="true"
			required="true" />
		<element name="E-Mail" target="email"
			regExp="[\w-\.]{3,}@([\w-]{2,}\.)*([\w-]{2,}\.)[\w-]{2,4}"
			invalidMessage="mail no valido" type="dijit-form-validation-text-box"
			visible="true" edit="true" add="true" />
		<element name="Perfil" target="acl_roles_id" defaultValue=""
			type="dijit-form-filtering-select" table="AclRolesModel" field="role_name"
			visible="true" edit="true" add="true" />
		<element name="Activo" target="approved" type="dijit-form-check-box"
			formatter="utils.formatYesNo" visible="true" edit="true" add="true" />
		<element name="Activo" target="acl_users.approved" type="dijit-form-check-box"
			formatter="utils.formatYesNo" visible="false" edit="false" add="false" />
		<!--<element name="Grupos" target="grupos" type="dojox-form-checked-multi-select" 
			table="AclGroupsModel" field="title" visible="false" edit="disabled" style="width:164px;"/> -->
	</elements>
	<searchers>
		<group name="Datos Personales">
			<element target="user_name" />
			<element target="first_names" />
			<element target="email" />
		</group>
		<element target="acl_roles_id" defaultText="Todo" operator="=" />
		<element target="acl_users.approved" operator="="
			type="dijit-form-filtering-select"
			data="[{id:' ', name: 'Todo'}, {id: '0', name: 'No'}, {id: '1', name: 'SÃ­'}]"
			trim="true" defaultValue=" " />
	</searchers>
	<forms ajax="true">
		<changePassword>
			<element target="password" />
		</changePassword>
	</forms>
</component>

=== Gamelena/tangerine-testing/web/application/components/personal-info.xml
<?xml version="1.0"?>
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="components.xsd" name="Informaci&amp;oacute;n"
    type="dojo-simple-crud" target="PersonalInfoModel" list="true"
    plugins="{}" edit="true" add="false" delete="false">
    <elements>
        <element name="ID" target="id"
            type="dijit-form-validation-text-box" visible="false" edit="false"
            add="false" />
        <element name="Usuario" target="user_name"
            type="dijit-form-validation-text-box" visible="true" edit="false"
            add="true" />
        <element name="Nombres" target="first_names"
            type="dijit-form-validation-text-box" visible="true" edit="true"
            add="true" />
        <element name="Apellidos" target="last_names"
            type="dijit-form-validation-text-box" visible="true" edit="true"
            add="true" />
        <element name="E-Mail" target="email"
            type="dijit-form-validation-text-box" regExp="[\w-\.]{3,}@([\w-]{2,}\.)*([\w-]{2,}\.)[\w-]{2,4}"
            invalidMessage="mail no valido" visible="true" edit="true"
            add="true" />
    </elements>
    <forms>
        <changePassword>
            <element target="password" />
        </changePassword>
    </forms>
</component>

=== Gamelena/tangerine-testing/web/application/components/graphic-traffic.xml
<?xml version="1.0"?>
<component name="M&amp;oacute;dulos" type="dojo-simple-crud"
	target="TestingTraficoModel" list="true" delete="true" edit="true" add="true"
	clone="true" serverPagination="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="components.xsd">
	<script>
		dojo.require('admtesting.trafficChart')
		var trafficChart = new admtesting.trafficChart();
	</script>
	<elements>
		<element name="Id" target="id" type="dijit-form-validation-text-box"></element>
		<element name="Usuario" target="usuario" type="dijit-form-validation-text-box"></element>
		<element name="M&amp;oacute;dulo" target="modulo" type="dijit-form-validation-text-box"></element>
		<element name="Operaci&amp;oacute;n" target="operacion" type="dijit-form-validation-text-box"></element>
		<element name="Estado" target="estado" type="dijit-form-validation-text-box"></element>
		<element name="Fecha" target="fecha" required="true" type="dijit-form-date-text-box"></element>
	</elements>
	<forms ajax="true"></forms>
	<searchers outsideContent="true">
		<element name="Desde" target="fecha" operator="&amp;gt;=" sufix=" 00:00:00"></element>
		<element name="Hasta" target="fecha" operator="&amp;lt;=" sufix=" 23:59:59"></element>
		<onSubmit>
			trafficChart.show(this.get('value'));
		</onSubmit>
	</searchers>
</component>
