=== Gamelena/tangerine-testing/web/application/components/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="component" type="componentType">
    </xsd:element>
    <xsd:complexType name="componentType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="elements" type="elementsType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="searchers" type="searchersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="forms" type="formsType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="script" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pane" type="paneType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="target" use="required" type="xsd:normalizedString"/>
        <xsd:attribute name="type" use="required" type="componentTypeType" />
        <xsd:attribute name="name" type="xsd:normalizedString" />
        <xsd:attribute name="list" type="xsd:boolean" />
        <xsd:attribute name="edit" type="xsd:boolean" />
        <xsd:attribute name="add" type="xsd:boolean"/>
        <xsd:attribute name="delete" type="xsd:boolean"/>
        <xsd:attribute name="clone" type="xsd:boolean"/>
        <xsd:attribute name="canSort" type="xsd:boolean"/>
        <xsd:attribute name="js" />
        <xsd:attribute name="jsForm" />
        <xsd:attribute name="style" />
        <xsd:attribute name="plugins" />
        <xsd:attribute name="containerDojoType" type="containerDojoTypeType" />
        <xsd:attribute name="chartXType" />
        <xsd:attribute name="chartXTarget" />
        <xsd:attribute name="chartXLabel" />
        <xsd:attribute name="chartYTarget" />
        <xsd:attribute name="chartYLabel" />
        <xsd:attribute name="chartItems" />
        <xsd:attribute name="onRowClick" />
        <xsd:attribute name="onRowDblClick" />
        <xsd:attribute name="onFetchComplete" />
        <xsd:attribute name="onShow" />
        <xsd:attribute name="cols" />
        <xsd:attribute name="titles" />
        <xsd:attribute name="items" />
        <xsd:attribute name="itemsDescription" />
        <xsd:attribute name="aclComponent" />
        <xsd:attribute name="serverPagination" type="xsd:boolean" />
        <xsd:attribute name="inheritsData" type="xsd:boolean" />
        <xsd:attribute name="chartDojoType" type="chartDojoTypeType" />
        <xsd:attribute name="chartDojoTheme" type="chartDojoThemeType" />
    </xsd:complexType>
    <xsd:complexType name="elementsType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="style" />
    </xsd:complexType>
    <xsd:complexType name="searchersType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="hideSubmit" type="xsd:boolean"/>
        <xsd:attribute name="outsideContent" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:complexType name="formsType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="changePassword" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="edit" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="add" type="formType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onPostSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onShow" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="tabs" type="tabsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="ajax" type="xsd:boolean" />
        <xsd:attribute name="style"/>
        <xsd:attribute name="onload"/>
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
        <xsd:attribute name="component"/>
    </xsd:complexType>
    <xsd:complexType name="formType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tabs" type="tabsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="onPostSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="onSubmit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="ajax" />
        <xsd:attribute name="style"/>
        <xsd:attribute name="onload"/>
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
    </xsd:complexType>
    <xsd:complexType name="helpersType">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="dialog" type="formsType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="customFunction" type="customFunctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="excel" type="excelType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="uploader" type="uploaderType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="PaneType">
        <xsd:attribute name="onshow"/>
        <xsd:attribute name="onhide"/>
        <xsd:attribute name="name"/>
    </xsd:complexType>
    <xsd:complexType name="tabsType">
        <xsd:sequence>
            <xsd:element name="tab" type="tabType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tabType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="helpers" type="helpersType" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="onClick" />
        <xsd:attribute name="dojoType" />
        <xsd:attribute name="style" />
    </xsd:complexType>
    <xsd:complexType name="paneType">
        <xsd:attribute name="name" />
        <xsd:attribute name="href" />
        <xsd:attribute name="onshow" />
    </xsd:complexType>
    <xsd:complexType name="groupType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" />
        <xsd:attribute name="type" type="elementTypeType"/>
        <xsd:attribute name="visible" type="xsd:boolean" />
        <xsd:attribute name="edit" type="editType" />
        <xsd:attribute name="add" type="editType" />
        <xsd:attribute name="clone" type="editType" />
        <xsd:attribute name="password" />
        <xsd:attribute name="defaultValue" />
        <xsd:attribute name="defaultText" />
        <xsd:attribute name="field" />
        <xsd:attribute name="required" type="xsd:boolean" />
        <xsd:attribute name="disabled" type="xsd:boolean" />
        <xsd:attribute name="readonly" type="xsd:boolean" />
        <xsd:attribute name="regExp"/>
        <xsd:attribute name="trim" type="xsd:boolean"/>
        <xsd:attribute name="table"/>
        <xsd:attribute name="tableField"/>
        <xsd:attribute name="tablePk"/>
        <xsd:attribute name="tableMethod"/>
        <xsd:attribute name="invalidMessage"/>
        <xsd:attribute name="promptMessage"/>
        <xsd:attribute name="list"/>
        <xsd:attribute name="formatter"/>
        <xsd:attribute name="maxlength"/>
        <xsd:attribute name="width"/>
        <xsd:attribute name="operator" type="operatorType"/>
    </xsd:complexType>
    <xsd:complexType name="customFunctionType">
        <xsd:attribute name="target"/>
        <xsd:attribute name="onclick"/>
        <xsd:attribute name="name"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="title"/>
        <xsd:attribute name="disabled" type="xsd:boolean"/>
    </xsd:complexType>
    <xsd:complexType name="excelType">
        <xsd:attribute name="name"/>
        <xsd:attribute name="formatter" type="excelFormatter"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="disabled" type="xsd:boolean"/>
    </xsd:complexType>
        <xsd:complexType name="uploaderType">
        <xsd:attribute name="name"/>
        <xsd:attribute name="path"/>
        <xsd:attribute name="iconClass"/>
        <xsd:attribute name="action" type="uploaderActionType"/>
        <xsd:attribute name="processClass"/><!-- @todo por implementar -->
        <xsd:attribute name="processMethod"/><!-- @todo por implementar -->
        <xsd:attribute name="truncate" type="xsd:boolean" />
    </xsd:complexType>
    <xsd:complexType name="elementType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="tinyMceInit" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="thumb" type="thumbType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="target" use="required"/>
        <xsd:attribute name="type" type="elementTypeType"/>
        <xsd:attribute name="style" />
        <xsd:attribute name="name" />
        <xsd:attribute name="visible" type="xsd:boolean" />
        <xsd:attribute name="edit" type="editType" />
        <xsd:attribute name="add" type="editType" />
        <xsd:attribute name="clone" type="editType" />
        <xsd:attribute name="value" />
        <xsd:attribute name="defaultValue" />
        <xsd:attribute name="uncheckedValue" />
        <xsd:attribute name="selectedTitle" type="xsd:string"/>
        <xsd:attribute name="unselectedTitle" type="xsd:string" />
        <xsd:attribute name="defaultText" type="xsd:string" />
        <xsd:attribute name="field" />
        <xsd:attribute name="onchange" />
        <xsd:attribute name="disabled" type="xsd:boolean" />
        <xsd:attribute name="onclick" />
        <xsd:attribute name="onkeypress" />
        <xsd:attribute name="onkeyup" />
        <xsd:attribute name="onblur" />
        <xsd:attribute name="onload" />
        <xsd:attribute name="required" type="xsd:boolean" />
        <xsd:attribute name="autocomplete" type="onOffType" />
        <xsd:attribute name="regExp"/>
        <xsd:attribute name="trim"/>
        <xsd:attribute name="url" type="xsd:anyURI"/>
        <xsd:attribute name="path"/>
        <xsd:attribute name="table"/>
        <xsd:attribute name="tableField"/>
        <xsd:attribute name="tablePk"/>
        <xsd:attribute name="tableMethod"/>
        <xsd:attribute name="invalidMessage"/>
        <xsd:attribute name="promptMessage"/>
        <xsd:attribute name="list"/>
        <xsd:attribute name="data"/>
        <xsd:attribute name="formatter"/>
        <xsd:attribute name="maxlength" type="xsd:integer"/>
        <xsd:attribute name="width"/>
        <xsd:attribute name="checked" type="xsd:boolean"/>
        <xsd:attribute name="sufix"/>
        <xsd:attribute name="prefix"/>
        <xsd:attribute name="tinyMceTemplate" />
        <xsd:attribute name="placeHolder" />
        <xsd:attribute name="operator" type="operatorType"/>
    </xsd:complexType>
    <xsd:complexType name="thumbType">
        <xsd:attribute name="width" />
        <xsd:attribute name="height" />
        <xsd:attribute name="path"/>
    </xsd:complexType>
    <xsd:simpleType name="onOffType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="on"/>
            <xsd:enumeration value="off"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="editType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="true"/>
            <xsd:enumeration value="false"/>
            <xsd:enumeration value="readonly"/>
            <xsd:enumeration value="disabled"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="uploaderActionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="load"/>
            <xsd:enumeration value="insert"/>
            <xsd:enumeration value="delete"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="excelFormatter">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Excel5"/>
            <xsd:enumeration value="Excel2007"/>
            <xsd:enumeration value="csv"/>
            <xsd:enumeration value="html"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="operatorType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="like"/>
            <xsd:enumeration value="between"/>
            <xsd:enumeration value="="/>
            <xsd:enumeration value="!="/>
            <xsd:enumeration value="&amp;gt;&amp;lt;"/>
            <xsd:enumeration value="&amp;gt;"/>
            <xsd:enumeration value="&amp;lt;"/>
            <xsd:enumeration value="&#38;gt;="/>
            <xsd:enumeration value="&#38;lt;="/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="componentTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dojo-chart"/>
            <xsd:enumeration value="dojo-settings"/>
            <xsd:enumeration value="dojo-simple-crud"/>
            <xsd:enumeration value="nodes-graph"/>
            <xsd:enumeration value="php-info"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="elementTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dijit-form-check-box"/>
            <xsd:enumeration value="dojox-form-checked-multi-select"/>
            <xsd:enumeration value="dojox-form-checked-multi-select-binary"/>
            <xsd:enumeration value="dijit-form-combo-box"/>
            <xsd:enumeration value="dijit-form-date-text-box"/>
            <xsd:enumeration value="dijit-form-filtering-select"/>
            <xsd:enumeration value="dijit-form-select"/>
            <xsd:enumeration value="dijit-form-textarea"/>
            <xsd:enumeration value="dijit-form-time-text-box"/>
            <xsd:enumeration value="dijit-form-validation-text-box"/>
            <xsd:enumeration value="dojox-form-uploader"/>
            <xsd:enumeration value="dojox-widget-color-picker"/>
            <xsd:enumeration value="dojo-dnd-source"/>
            <xsd:enumeration value="hidden"/>
            <xsd:enumeration value="list-files"/>
            <xsd:enumeration value="tiny-mce"/>
            <xsd:enumeration value="zwei-form-validation-textarea"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="chartDojoTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Areas"/>
            <xsd:enumeration value="Bars"/>
            <xsd:enumeration value="Base"/>
            <xsd:enumeration value="Bubble"/>
            <xsd:enumeration value="Candlesticks"/>
            <xsd:enumeration value="CartesianBase"/>
            <xsd:enumeration value="ClusteredBars"/>
            <xsd:enumeration value="ClusteredColumns"/>
            <xsd:enumeration value="Columns"/>
            <xsd:enumeration value="Default"/>
            <xsd:enumeration value="Grid"/>
            <xsd:enumeration value="Lines"/>
            <xsd:enumeration value="Markers"/>
            <xsd:enumeration value="MarkersOnly"/>
            <xsd:enumeration value="OHLC"/>
            <xsd:enumeration value="Pie"/>
            <xsd:enumeration value="Scatter"/>
            <xsd:enumeration value="Spider"/>
            <xsd:enumeration value="Stacked"/>
            <xsd:enumeration value="StackedAreas"/>
            <xsd:enumeration value="StackedBars"/>
            <xsd:enumeration value="StackedColumns"/>
            <xsd:enumeration value="StackedLines"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="chartDojoThemeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Adobebricks"/>
            <xsd:enumeration value="Algae"/>
            <xsd:enumeration value="Bahamation"/>
            <xsd:enumeration value="BlueDusk"/>
            <xsd:enumeration value="Charged"/>
            <xsd:enumeration value="Chris"/>
            <xsd:enumeration value="Claro"/>
            <xsd:enumeration value="CubanShirts"/>
            <xsd:enumeration value="Desert"/>
            <xsd:enumeration value="Distinctive"/>
            <xsd:enumeration value="Dollar"/>
            <xsd:enumeration value="Electric"/>
            <xsd:enumeration value="Grasshoper"/>
            <xsd:enumeration value="Grasslands"/>
            <xsd:enumeration value="GreySkies"/>
            <xsd:enumeration value="Harmony"/>
            <xsd:enumeration value="IndigoNation"/>
            <xsd:enumeration value="Ireland"/>
            <xsd:enumeration value="Julie"/>
            <xsd:enumeration value="MiamiNice"/>
            <xsd:enumeration value="Midwest"/>
            <xsd:enumeration value="Minty"/>
            <xsd:enumeration value="PrimaryColors"/>
            <xsd:enumeration value="PurpleRain"/>
            <xsd:enumeration value="Renkoo"/>
            <xsd:enumeration value="RoyalPurples"/>
            <xsd:enumeration value="SageToLime"/>
            <xsd:enumeration value="Shrooms"/>
            <xsd:enumeration value="Threed"/>
            <xsd:enumeration value="Tom"/>
            <xsd:enumeration value="Tufte"/>
            <xsd:enumeration value="WatersEdge"/>
            <xsd:enumeration value="Wetland"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="containerDojoTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="dijit/layout/BorderContainer"/>
            <xsd:enumeration value="dijit/layout/AccordionContainer"/>
            <xsd:enumeration value="dijit/layout/TabContainer"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Gamelena/tangerine-testing/web/application/components/abonados.xml
<?xml version="1.0"?>
<component name="Abonados" type="dojo-simple-crud"
	target="DbTable_TestingAbonados" list="true" delete="true" edit="true" add="true"
	clone="true" serverPagination="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="components.xsd">
	<elements>
		<element name="MSISDN" target="msisdn" type="dijit-form-validation-text-box"
			visible="true" edit="true" add="true" clone="true" maxlength="11" regExp="[\d]{11}" required="true"></element>
		<element name="Lista" target="list" type="dijit-form-validation-text-box"
			visible="true" edit="true" add="true" clone="true" regExp="[\d]+" maxlength="2" required="true"></element>
	</elements>
	<forms ajax="true"></forms>
	<helpers>
		<excel name="Descargar CSV" formatter="csv" iconClass="zweiIconDownload" />
		<uploader name="Carga Masiva CSV" action="load" iconClass="zweiIconUpload" />
		<uploader name="Inserción Masiva" action="insert" iconClass="zweiIconUpload"/>
		<uploader name="Borrado e Inserción Masiva" action="insert" truncate="true" iconClass="zweiIconUpload"/>
		<uploader name="Eliminación Masiva" action="delete" iconClass="zweiIconUpload"/>
	</helpers>
	<searchers>
		<element target="msisdn" required="false"></element>
	</searchers>
</component>

=== Gamelena/tangerine-testing/web/application/components/settings-advanced.xml
<?xml version="1.0"?>
<component name="Configuraci&amp;oacute;n" type="dojo-simple-crud"
    target="SettingsModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="components.xsd" list="true" edit="true"
    add="true">
    <elements>
        <element name="Variable" target="id"
            type="dijit-form-validation-text-box" regExp="^\w+$"
            required="true" edit="disabled" add="true" visible="true"></element>
        <element name="DescripciÃ³n" target="description"
            type="dijit-form-validation-text-box" visible="true" edit="true"
            add="true"></element>
        <element name="Tipo" target="type"
            type="dijit-form-filtering-select"
            list="dijit-form-check-box;dijit-form-combo-box;dijit-form-date-text-box;dijit-form-filtering-select;dijit-form-textarea;dijit-form-validation-text-box;dojox-form-checked-multi-select;dojox-form-checked-multi-select-binary;dojox-form-uploader;tiny-mce-zwei-form-validation-textarea"
            edit="true" add="true" visible="true"></element>
        <element name="Valor" target="value"
            type="dijit-form-validation-text-box" edit="false" add="true"
            visible="true"></element>
        <element name="Path" target="path"
            type="dijit-form-validation-text-box" edit="true" add="true"
            visible="true"></element>
        <element name="URL" target="url"
            type="dijit-form-validation-text-box" edit="true" add="true"
            visible="true"></element>
        <element name="XML Anidado" target="xml_children" type="dijit-form-textarea"
            style="height:3em;" edit="true" add="true" visible="true"
            required="false"></element>
        <element name="Aprobado" target="approved" type="dijit-form-check-box"
            edit="true" add="true" visible="true" formatter="utils.formatYesNo"></element>
    </elements>
    <forms ajax="true"></forms>
    <searchers>
        <element target="id" required="false"></element>
        <element target="description"></element>
        <element target="type" defaultValue="" defaultText=""></element>
    </searchers>
</component>

=== Gamelena/tangerine-testing/web/application/components/roles.xml
<?xml version="1.0"?>
<component name="Perfiles" type="dojo-simple-crud" target="AclRolesModel"
    js="roles.js" list="true" edit="true" add="true" clone="true"
    delete="true" plugins="{}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="components.xsd">
    <elements>
        <element name="ID" target="id"
            type="dijit-form-validation-text-box" visible="true" edit="false"
            add="false" />
        <element name="Perfil" target="role_name"
            type="dijit-form-validation-text-box" required="true" trim="true"
            visible="true" edit="true" add="true" clone="true" />
        <element name="Descripci&amp;oacute;n" target="description"
            type="dijit-form-textarea"
            style="color: #131313;font-family: Arial,Helvetica,sans-serif;font-size: inherit;"
            visible="true" edit="true" add="true" clone="true" />
        <element name="Permisos" target="permissions"
            type="dojo-dnd-source" table="AclModulesActionsModel"
            tableMethod="selectAllActions" visible="false" edit="true"
            add="true" clone="true" style="height:450px !important;" selectedTitle="Permisos seleccionados" unselectedTitle="Permisos" />
    </elements>
    <searchers>
        <group name="Perfil">
            <element target="role_name" />
            <element target="description" />
        </group>
    </searchers>
    <forms ajax="true" style="min-height:85%;min-width:30%;"
        onload="dojo.byId(this.id).style.minHeight=null;dojo.byId(this.id).style.minWidth=null;"
        onhide="dojo.byId(this.id).style.minHeight='85%';dojo.byId(this.id).style.minWidth='30%';">
        <tabs>
            <tab name="Informaci&amp;oacute;n B&amp;aacute;sica">
                <element target="role_name" />
                <element target="description" />
            </tab>
            <tab name="Permisos" onClick="
            	if (!$globals[this.parentElement.id + 'centered']) { 
            		utils.centerDialog(dijit.byId(this.parentElement.id).getParent()); 
            		$globals[this.parentElement.id + 'centered'] = true;
        		}">
                <element target="permissions" />
            </tab>
        </tabs>
        <onShow>
        	$globals[this.id + 'centered'] = false;	
            dojo.query('#'+this.id+' .dndContainer').forEach(function(container) {container.style.width='26em'});
        </onShow>
    </forms>
</component>

=== Gamelena/tangerine-testing/web/application/components/online-sessions.xml
<?xml version="1.0"?>
<component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="components.xsd" name="Sesiones"
    type="dojo-simple-crud" target="AclSessionOnlineModel" list="true"
    edit="false" add="false" delete="true">
    <elements>
        <element name="Id de Sesión" target="id"
            type="dijit-form-validation-text-box" visible="true" />
        <element name="Usuario" target="user_name"
            type="dijit-form-validation-text-box" visible="true" />
        <element name="Perfil" target="role_name"
            type="dijit-form-validation-text-box" visible="true" />
        <element name="IP" target="ip"
            type="dijit-form-validation-text-box" visible="true" />
        <element name="E-Mail" target="email"
            type="dijit-form-validation-text-box" />
        <element name="Última actividad" target="modified"
            type="dijit-form-validation-text-box" visible="true" />
    </elements>
</component>

=== Gamelena/tangerine-testing/web/application/components/groups.xml
<!DOCTYPE section PUBLIC "//COMPONENTS/" "components.dtd">
<component name="Grupos" type="dojo-simple-crud" target="AclGroupsModel" edit="true" add="true" delete="true" list="true" clone="true" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="components.xsd" style="min-height:427px;width:417px;">
    <elements>
        <element name="Nombre" target="title" required="true" type="dijit-form-validation-text-box" visible="true" edit="true" add="true"></element>
        <element name="Descripción" target="description" type="dijit-form-validation-text-box" visible="true" edit="true" add="true"></element>
    </elements>
    <forms ajax="true">
        <tabs>
            <tab name="Datos Básicos">
                <element target="title"/>
                <element target="description"/> 
            </tab>
            <tab name="Usuarios">
                <element name="Usuarios" target="usuarios" type="dojox-form-checked-multi-select" table="AclUsersModel" field="user_name" visible="true" edit="true" add="true"/>
            </tab>
        </tabs>
    </forms>
</component>
